import { useEffect, useState } from 'react'
import { api } from '../services/api'

type FraudAlert = {
  id: string
  candidate_id: string
  alert_type: string
  severity: string
  confidence_score: number
  description: string
  evidence: Record<string, unknown>
  created_at: string
}

type AlertResponse = {
  total_alerts: number
  by_severity: Record<string, number>
  recent_alerts: FraudAlert[]
}

export default function FraudAlerts() {
  const [alerts, setAlerts] = useState<AlertResponse | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    async function loadAlerts() {
      try {
        const response = await api.getFraudAlerts()
        setAlerts(response.data)
      } catch (error) {
        console.error('Fraud alerts load failed', error)
      } finally {
        setLoading(false)
      }
    }
    loadAlerts()
  }, [])

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-semibold text-white">Fraud Alerts</h1>
        <p className="mt-3 text-slate-400 max-w-2xl">Review candidate risk signals and evidence generated by TalentGraph.</p>
      </div>

      <div className="grid gap-6 lg:grid-cols-[320px_1fr]">
        <div className="rounded-[32px] border border-white/10 bg-slate-900/95 p-7 shadow-[0_28px_80px_rgba(15,23,42,0.35)]">
          <h2 className="text-xl font-semibold text-white">Alert summary</h2>
          <p className="mt-2 text-sm text-slate-400">Severity counts from recent fraud detections.</p>
          <div className="mt-6 space-y-4">
            {loading ? (
              <div className="rounded-3xl border border-slate-800 bg-slate-950/95 p-5 text-slate-400">Loading alert summary...</div>
            ) : alerts ? (
              Object.entries(alerts.by_severity).map(([severity, count]) => (
                <div key={severity} className="rounded-3xl border border-slate-800 bg-slate-950/95 p-5 shadow-sm shadow-slate-950/10">
                  <p className="text-sm uppercase tracking-[0.2em] text-slate-500">{severity}</p>
                  <p className="mt-3 text-3xl font-semibold text-white">{count}</p>
                </div>
              ))
            ) : (
              <div className="rounded-3xl border border-slate-800 bg-slate-950/95 p-5 text-slate-400">No fraud alerts are available.</div>
            )}
          </div>
        </div>

        <div className="rounded-[32px] border border-white/10 bg-slate-900/95 p-7 shadow-[0_28px_80px_rgba(15,23,42,0.35)]">
          <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <h2 className="text-xl font-semibold text-white">Recent alerts</h2>
              <p className="mt-2 text-sm text-slate-400">Review suspicious candidate submissions and evidence details.</p>
            </div>
            <span className="inline-flex rounded-2xl bg-slate-800 px-4 py-2 text-sm text-slate-200 shadow-inner shadow-slate-950/20">{loading ? 'Loading...' : alerts?.total_alerts ?? 0} alerts</span>
          </div>

          <div className="mt-8 overflow-hidden rounded-3xl border border-slate-800 bg-slate-950/95 shadow-inner shadow-slate-950/10">
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-slate-800 text-left text-sm text-slate-300">
                <thead className="bg-slate-900 text-slate-400">
                  <tr>
                    <th className="px-4 py-4">Candidate</th>
                    <th className="px-4 py-4">Type</th>
                    <th className="px-4 py-4">Severity</th>
                    <th className="px-4 py-4">Confidence</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800">
                  {loading ? (
                    <tr>
                      <td className="px-4 py-10 text-slate-500" colSpan={4}>
                        Loading fraud alerts...
                      </td>
                    </tr>
                  ) : alerts?.recent_alerts.length ? (
                    alerts.recent_alerts.map((alert) => (
                      <tr key={alert.id} className="transition hover:bg-slate-900/80">
                        <td className="px-4 py-4">{alert.candidate_id}</td>
                        <td className="px-4 py-4">{alert.alert_type}</td>
                        <td className="px-4 py-4 capitalize">{alert.severity}</td>
                        <td className="px-4 py-4">{Math.round(alert.confidence_score * 100)}%</td>
                      </tr>
                    ))
                  ) : (
                    <tr>
                      <td className="px-4 py-10 text-slate-500" colSpan={4}>
                        No fraud alerts detected.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
