import { useEffect, useState } from 'react'
import { api } from '../services/api'

type FraudAlert = {
  id: string
  candidate_id: string
  alert_type: string
  severity: string
  confidence_score: number
  description: string
  evidence: Record<string, unknown>
  created_at: string
}

type AlertResponse = {
  total_alerts: number
  by_severity: Record<string, number>
  recent_alerts: FraudAlert[]
}

export default function FraudAlerts() {
  const [alerts, setAlerts] = useState<AlertResponse | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    async function loadAlerts() {
      try {
        const response = await api.getFraudAlerts()
        setAlerts(response.data)
      } catch (error) {
        console.error('Fraud alerts load failed', error)
      } finally {
        setLoading(false)
      }
    }
    loadAlerts()
  }, [])

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-bold text-white">Fraud Alerts</h1>
        <p className="mt-3 text-slate-400 max-w-2xl">Review candidate risk signals and evidence generated by TalentGraph.</p>
      </div>

      <div className="grid gap-6 lg:grid-cols-[300px_1fr]">
        <div className="rounded-[32px] border border-slate-800 bg-slate-950/90 p-6 shadow-2xl shadow-slate-950/20">
          <h2 className="text-xl font-semibold text-white">Alert summary</h2>
          <p className="mt-2 text-sm text-slate-400">Severity counts from recent fraud detections.</p>
          <div className="mt-6 space-y-3">
            {loading ? (
              <p className="text-slate-400">Loading alert summary...</p>
            ) : alerts ? (
              Object.entries(alerts.by_severity).map(([severity, count]) => (
                <div key={severity} className="rounded-3xl border border-slate-800 bg-slate-900/80 p-4">
                  <p className="text-sm uppercase tracking-[0.2em] text-slate-500">{severity}</p>
                  <p className="mt-2 text-2xl font-semibold text-white">{count}</p>
                </div>
              ))
            ) : (
              <p className="text-slate-400">No fraud alerts are available.</p>
            )}
          </div>
        </div>

        <div className="rounded-[32px] border border-slate-800 bg-slate-950/90 p-6 shadow-2xl shadow-slate-950/20">
          <div className="flex items-center justify-between gap-4">
            <div>
              <h2 className="text-xl font-semibold text-white">Recent alerts</h2>
              <p className="mt-2 text-sm text-slate-400">Review suspicious candidate submissions and evidence details.</p>
            </div>
            <span className="rounded-2xl bg-slate-900 px-4 py-2 text-sm text-slate-200">{loading ? 'Loading...' : alerts?.total_alerts ?? 0} alerts</span>
          </div>

          <div className="mt-8 overflow-hidden rounded-3xl border border-slate-800 bg-slate-900/60">
            <table className="min-w-full divide-y divide-slate-800 text-left text-sm text-slate-300">
              <thead className="bg-slate-950/95 text-slate-400">
                <tr>
                  <th className="px-4 py-4">Candidate</th>
                  <th className="px-4 py-4">Type</th>
                  <th className="px-4 py-4">Severity</th>
                  <th className="px-4 py-4">Confidence</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800">
                {loading ? (
                  <tr>
                    <td className="px-4 py-6 text-slate-500" colSpan={4}>
                      Loading fraud alerts...
                    </td>
                  </tr>
                ) : alerts?.recent_alerts.length ? (
                  alerts.recent_alerts.map((alert) => (
                    <tr key={alert.id} className="hover:bg-slate-900/80">
                      <td className="px-4 py-4">{alert.candidate_id}</td>
                      <td className="px-4 py-4">{alert.alert_type}</td>
                      <td className="px-4 py-4 capitalize">{alert.severity}</td>
                      <td className="px-4 py-4">{Math.round(alert.confidence_score * 100)}%</td>
                    </tr>
                  ))
                ) : (
                  <tr>
                    <td className="px-4 py-6 text-slate-500" colSpan={4}>
                      No fraud alerts detected.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  )
}
